language: python
sudo: yes
python:
  - "3.5"
  - "3.6"

before_install:
   - sudo apt-get -qq update
   - sudo apt-get install -y libspatialindex-dev

install:
   - "pip install -r requirements.txt"
   - pip install https://github.com/MatthewDaws/TileMapBase/zipball/master

script:
  - pytest --cov=./
  
after_success:
  - codecov
